"""Database package — all persistence goes through here."""
from __future__ import annotations

from db._base import (  # noqa: F401
    EXPECTED_SCHEMA,
    check_schema,
    get_postgrest_url,
    storage_backend_name,
    use_postgres,
    use_postgrest,
)

if use_postgres():
    from db.postgres import (  # noqa: F401
        add_up_notify,
        check_connection,
        clear_bothunter_config,
        clear_rate_notification,
        clear_ark_notification,
        clear_up_notify,
        get_bothunter_channel_map,
        get_bothunter_config,
        get_bothunter_moderated_count,
        get_karma_settings,
        get_previous_rate_values,
        get_previous_ark_notice,
        get_rate_notification,
        get_rate_notification_channels,
        get_ark_notification,
        get_ark_notification_channels,
        get_server_player_history,
        karma_add,
        karma_get_audit,
        karma_get_balance,
        karma_get_cooldown,
        karma_get_history,
        karma_take,
        list_up_notify_keys,
        list_up_notify_watchers,
        list_watched_server_keys,
        log_bothunter_event,
        prune_server_samples,
        record_server_sample,
        save_previous_rate_values,
        save_previous_ark_notice,
        set_bothunter_config,
        set_rate_notification,
        set_ark_notification,
        watch_server,
    )
elif use_postgrest():
    from db.postgrest import (  # noqa: F401
        add_up_notify,
        check_connection,
        clear_bothunter_config,
        clear_rate_notification,
        clear_ark_notification,
        clear_up_notify,
        get_bothunter_channel_map,
        get_bothunter_config,
        get_bothunter_moderated_count,
        get_karma_settings,
        get_previous_rate_values,
        get_previous_ark_notice,
        get_rate_notification,
        get_rate_notification_channels,
        get_ark_notification,
        get_ark_notification_channels,
        get_server_player_history,
        karma_add,
        karma_get_audit,
        karma_get_balance,
        karma_get_cooldown,
        karma_get_history,
        karma_take,
        list_up_notify_keys,
        list_up_notify_watchers,
        list_watched_server_keys,
        log_bothunter_event,
        prune_server_samples,
        record_server_sample,
        save_previous_rate_values,
        save_previous_ark_notice,
        set_bothunter_config,
        set_rate_notification,
        set_ark_notification,
        watch_server,
    )
else:
    from db.files import (  # noqa: F401
        add_up_notify,
        clear_bothunter_config,
        clear_rate_notification,
        clear_ark_notification,
        clear_up_notify,
        get_bothunter_channel_map,
        get_bothunter_config,
        get_bothunter_moderated_count,
        get_karma_settings,
        get_previous_rate_values,
        get_previous_ark_notice,
        get_rate_notification,
        get_rate_notification_channels,
        get_ark_notification,
        get_ark_notification_channels,
        get_server_player_history,
        karma_add,
        karma_get_audit,
        karma_get_balance,
        karma_get_cooldown,
        karma_get_history,
        karma_take,
        list_up_notify_keys,
        list_up_notify_watchers,
        list_watched_server_keys,
        log_bothunter_event,
        prune_server_samples,
        record_server_sample,
        save_previous_rate_values,
        save_previous_ark_notice,
        set_bothunter_config,
        set_rate_notification,
        set_ark_notification,
        watch_server,
    )

    def check_connection() -> None:
        """JSON file backend — no remote connection to verify."""
        return None
